env:
  global:
    - PROJECT_NAME=bkt-odp
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    #- secure: "hB/9KoanqxBUKoJwKH8WWbzI7oFbxVhjEA0shWLki346UjnZUQprNNjof7KgA06ADUUfsBuf02DU4dJBGCdU9o/RQm4kFJOz8TgcJzS9n5nTsN2B+0nFc/mJIp1qyMKn4j7p3fylDYAuz8szNKmCwXa6n8by0mtPJ6j7pgNK2f4xzzWB2x3f7wP7sXhhJkwJUXYjii1NC1zR5hwcP0TJl8X9opJRgNGwABU7mTkMNf1QxkYUK3VyyE7clOSYMr4DRB9aq+fjeykeuKuFqIk+vjk3Nb2LaroRcWAU8fDke14M71zYfH0opjGnezb12j3NU58VrESbjL/C5p/3bECfPJsvzmdhwfnVgdZvx1+gWjhHWqnm9YQbmc7+EYuO+T2guXa7dKxcn5oU7O/QiBRG4hKsubFHwFfZNG7hblDwDo4+V0tz+02T7mI6Ka3T6jVLSgt3t+ScfY10HyKKxRLdWldskLwxI47Tm6ZU8gL3Gjzfv2zV6okr/Cv+r5hjxvPTxeXqVicBZ/NqYawSrhnEMyzFWizqfeTjJAjp+AMX6nWK4820ETvwD/s+gzV3cj8ESErM2N+yabWzGkwC/B6gibpjEnKbeSNbs6eQaPUm4d2U0YfGSPf8vJeQ47iwJhohMLYppnVM1omyFohvR06HPiDhtEj5MOviXYMoKs0is7c="
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    - secure: "P/y5Yns4dUjr2pqAvoxo8JymPlYGPMdbg5/8iTPYN3pYOgbNYzexa6/w4abErBUCZ9o3tI9ylQTUspQAQncE9Jk5EfD8ZvGrdyd9UbaB0hZA5ddMbJuwwbjgrNBT0zVTvmU1JrNNhQnao7UTLEo+yQrkFKsm6wldbdwwrpaFeiaCYcgFUl7Ft+1ywoMONKCNMeO7h8wY9F4kc1X2vSF+MUFKb65gieWBuL3d01b/hncdXzR7+HMQdrfADf3CN7jaNTX/S7awQaLQzmBGa3EetbqVR+5hZOigRA0cxAfTQKptBsQwvX5S1XLP0LDfMXjCWdcCP8L40uBFc5J8Qb3VTeH/2VrAWh8aV+P7pPZrAAq4jSPb4vBH4Mn5C5M2OSnICLhYDhRzISA5r+uvv4n0zcK3TYsO6QEwzeMLDg7W9TthcSGCZ8PJnAU1MdSa4nYWUgyWZ+iqcLENRgqyOyGdcGsc9tNUr/QrY9lhmpfuABlvhJBzsT+yYb00chWO3zcOdWOqrJM2hVnS0AsEYY4caoD/6oC52dok0sYTZ8ODqoACXQ44Fx++cVD+bskowNERBG6+jQXoDdjQzNmB7wSRIde9eCNlNEAITSWlDMav4EZ5PrAA8K7VOBKDtqNUZ6K/XXtrgq/3gK044enH4XTPYZwxXrsCGNhv44/pqJIAA7Q="
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta