env:
  global:
    - PROJECT_NAME=bkt-odp
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    #- secure: "hB/9KoanqxBUKoJwKH8WWbzI7oFbxVhjEA0shWLki346UjnZUQprNNjof7KgA06ADUUfsBuf02DU4dJBGCdU9o/RQm4kFJOz8TgcJzS9n5nTsN2B+0nFc/mJIp1qyMKn4j7p3fylDYAuz8szNKmCwXa6n8by0mtPJ6j7pgNK2f4xzzWB2x3f7wP7sXhhJkwJUXYjii1NC1zR5hwcP0TJl8X9opJRgNGwABU7mTkMNf1QxkYUK3VyyE7clOSYMr4DRB9aq+fjeykeuKuFqIk+vjk3Nb2LaroRcWAU8fDke14M71zYfH0opjGnezb12j3NU58VrESbjL/C5p/3bECfPJsvzmdhwfnVgdZvx1+gWjhHWqnm9YQbmc7+EYuO+T2guXa7dKxcn5oU7O/QiBRG4hKsubFHwFfZNG7hblDwDo4+V0tz+02T7mI6Ka3T6jVLSgt3t+ScfY10HyKKxRLdWldskLwxI47Tm6ZU8gL3Gjzfv2zV6okr/Cv+r5hjxvPTxeXqVicBZ/NqYawSrhnEMyzFWizqfeTjJAjp+AMX6nWK4820ETvwD/s+gzV3cj8ESErM2N+yabWzGkwC/B6gibpjEnKbeSNbs6eQaPUm4d2U0YfGSPf8vJeQ47iwJhohMLYppnVM1omyFohvR06HPiDhtEj5MOviXYMoKs0is7c="
    # beta
    - secure: "L5fAqvTBTZvhyyv86tC4pXla/IZ6B1y1t0ykb7g/2MUHxsDR8EmsyVW+n+cYy/bhXa3BNusqYVvW1AZE2ZNPO5yBr54AQvO8ahr/p2OUV6azSzKO9BtoCRzTtqfBwo+4l0BVLMYbhmracGmSgr7hD+P7IZ6yO1C8IxghJAWAYk5/gqjzW2jNtXeHqT7r9TFDQsWEHOb9GcpcZaOG+Zt/bLhm99c2rHkigdXnkAh78URSFD8LX24OaHjdpNUMBgCHuN2fMoOUmON7I/TeUA9H0vKoFThD0/OMS6M5poDrwakTvCC2eqqUrocpUiDfZ3XvGkbkJS4R1auF35Z2la7vCnHKAWu/U9tJSWJ1Huy7HKpLgo8aPp4FkAxkXUR9kf2sqAVZ4QXXpTcAI7Z/5pVhYtwkMRYUKX/NnVpZOiY1wohwUmds4wRe6vp27q/S2NR8LadvrWrKUrgpjvqC4sxEqYXensLbpPU3oGlfzBsbOG4fj8faYBJOtoOmsXs+mjdJjo0ebs+pcfRvFTQhA3CxQItUc2HbR6LqhCBgIki+xMY0qYrzop3UhdjWghPbKtfiEUj3Ul3pfNT9+fP1uC17RHZ3sdlLlQ2Gs9IRZdUS7+D7OIym7/0yAB3O2Waaggushx81tTGYN6RwhOrni043aOxlyrwGM7RoKJUZEArDGiw="
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta